apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: v2deploy
  name: v2deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: v2deploy
    spec:
      containers:
      - image: docker.io/testdocker9spring/spring-boot-rest-v2
        name: spring-boot-rest-v2
        resources: {}
status: {}
